name: movie_app
description: A movie list app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  splashscreen: ^1.2.0
  firebase_core: ^1.4.0
  firebase_analytics: ^5.0.2
  firebase_auth: ^3.0.1
  image_picker: ^0.8.3+2
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  path: ^1.8.0
  firebase_storage: ^10.0.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/splash_movie.png
